### ISSUE TITLE
Feature Request: Allow icons to be inserted inline

### ISSUE THREAD

**Issue by andersnoren** [ndiego/icon-block#39]
It would be fantastic to be able to insert icons inline, similar to how you can insert an `Inline image` in Core.

![image](https://github.com/ndiego/icon-block/assets/8181091/ffe90e8d-f251-42ac-8405-a94371398283)

**Comment by ndiego** [comment]
Yeah, I agree. Unfortunately, that would need to be done with a separate plugin since inline images are not actually instances of the Image block. This would be like my [experimental plugin](https://github.com/ndiego/enable-button-icons) that adds icons to buttons. Given the rules of the WP Plugins repo, if I were to add such functionality to the Icon Block, it would no longer be classified as a single block plugin and insertable from the Block Directory. 

<img width="574" alt="image" src="https://github.com/ndiego/icon-block/assets/4832319/bd09966e-bea3-4780-91a2-17891b986880">
